---
abstract: 'L10N support for Amon2'
author:
  - 'Kazuhiro Osawa <yappo {at} shibuya {dot} pl>'
build_requires:
  Test::More: 0.88
  Test::WWW::Mechanize::PSGI: 0
configure_requires:
  Module::Build::Tiny: 0.017
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2-Plugin-L10N
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Amon2: 0
  File::Find::Rule: 0
  HTTP::AcceptLanguage: 0.01
  Locale::Maketext: 0
  Locale::Maketext::Extract: 0
  Locale::Maketext::Extract::Plugin::Xslate: 0
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/yappo/p5-Amon2-Plugin-L10N/issues
  homepage: https://github.com/yappo/p5-Amon2-Plugin-L10N
  repository: https://github.com/yappo/p5-Amon2-Plugin-L10N.git
version: v0.1.1
x_contributors:
  - 'Kazuhiro Osawa <yappo@shibuya.pl>'
